<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Concesionario_model extends CI_Model
{

    public $table = 'concesionario';
    public $id = 'idconcesinario';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);

           return  $this->db->query("SELECT concesionario.idconcesinario, concesionario.nombre, concesionario.ape_pat , concesionario.ape_mat, concesionario.direccion , concesionario.telefono , concesionario.correo, concesionario.contrasena ,concesionario.direccion_doc, concesionario.clave,estatus.descripcion FROM concesionario, estatus WHERE estatus.clave=concesionario.clave")->result();
    }

     function lista()
        {
    return  $this->db->query("SELECT * FROM `estatus`")->result();
        }

        function get_clave(){

    // armamos la consulta
    $query = $this->db-> query('SELECT clave,descripcion FROM estatus');

    // si hay resultados
    if ($query->num_rows() > 0) {
        // almacenamos en una matriz bidimensional
        foreach($query->result() as $row)
           $arrDatos[htmlspecialchars($row->clave, ENT_QUOTES)] = 
htmlspecialchars($row->descripcion, ENT_QUOTES);

        $query->free_result();
        return $arrDatos;
     }
}

    // get data by id
    function get_by_id($id)
    {
        return  $this->db->query("SELECT concesionario.idconcesinario,concesionario.nombre, concesionario.ape_pat , concesionario.ape_mat, concesionario.direccion , concesionario.telefono , concesionario.correo, concesionario.contrasena ,concesionario.direccion_doc, concesionario.clave,estatus.descripcion FROM concesionario, estatus WHERE estatus.clave=concesionario.clave and concesionario.idconcesinario =". $id)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idconcesinario', $q);
	$this->db->or_like('nombre', $q);
	$this->db->or_like('ape_pat', $q);
	$this->db->or_like('ape_mat', $q);
	$this->db->or_like('direccion', $q);
	$this->db->or_like('telefono', $q);
	$this->db->or_like('correo', $q);
	$this->db->or_like('contrasena', $q);
	$this->db->or_like('direccion_doc', $q);
	$this->db->or_like('clave', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idconcesinario', $q);
	$this->db->or_like('nombre', $q);
	$this->db->or_like('ape_pat', $q);
	$this->db->or_like('ape_mat', $q);
	$this->db->or_like('direccion', $q);
	$this->db->or_like('telefono', $q);
	$this->db->or_like('correo', $q);
	$this->db->or_like('contrasena', $q);
	$this->db->or_like('direccion_doc', $q);
	$this->db->or_like('clave', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
     

}

/* End of file Concesionario_model.php */
/* Location: ./application/models/Concesionario_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-15 18:44:19 */
/* http://harviacode.com */