<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Conductor_model extends CI_Model
{

    public $table = 'conductor';
    public $id = 'idconductor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return  $this->db->query("SELECT conductor.idconductor, conductor.nombre_conductor,conductor.ap_conductor,conductor.am_conductor,conductor.push_c,conductor.permisoconducir,conductor.correo_conductor,conductor.contrasena,conductor.iniciohorario,conductor.finhorario,conductor.latitud,conductor.longitud,conductor.clave,estatus.descripcion FROM `conductor`,estatus WHERE estatus.clave=conductor.clave")->result();

    }
    function lista()
        {
    return  $this->db->query("SELECT * FROM `estatus`")->result();
        }

        function get_clave(){

    // armamos la consulta
    $query = $this->db-> query('SELECT clave,descripcion FROM estatus');

    // si hay resultados
    if ($query->num_rows() > 0) {
        // almacenamos en una matriz bidimensional
        foreach($query->result() as $row)
           $arrDatos[htmlspecialchars($row->clave, ENT_QUOTES)] = 
htmlspecialchars($row->descripcion, ENT_QUOTES);

        $query->free_result();
        return $arrDatos;
     }
}

    // get data by id
    function get_by_id($id)
    {
        return  $this->db->query("SELECT conductor.idconductor, conductor.nombre_conductor,conductor.ap_conductor,conductor.am_conductor,conductor.push_c,conductor.permisoconducir,conductor.correo_conductor,conductor.contrasena,conductor.iniciohorario,conductor.finhorario,conductor.latitud,conductor.longitud,conductor.clave,estatus.descripcion FROM `conductor`,estatus WHERE estatus.clave=conductor.clave and conductor.idconductor =". $id)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idconductor', $q);
	$this->db->or_like('nombre_conductor', $q);
	$this->db->or_like('ap_conductor', $q);
	$this->db->or_like('am_conductor', $q);
	$this->db->or_like('correo_conductor', $q);
	$this->db->or_like('contrasena', $q);
	$this->db->or_like('push_c', $q);
	$this->db->or_like('permisoconducir', $q);
	$this->db->or_like('iniciohorario', $q);
	$this->db->or_like('finhorario', $q);
	$this->db->or_like('latitud', $q);
	$this->db->or_like('longitud', $q);
	$this->db->or_like('clave', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idconductor', $q);
	$this->db->or_like('nombre_conductor', $q);
	$this->db->or_like('ap_conductor', $q);
	$this->db->or_like('am_conductor', $q);
	$this->db->or_like('correo_conductor', $q);
	$this->db->or_like('contrasena', $q);
	$this->db->or_like('push_c', $q);
	$this->db->or_like('permisoconducir', $q);
	$this->db->or_like('iniciohorario', $q);
	$this->db->or_like('finhorario', $q);
	$this->db->or_like('latitud', $q);
	$this->db->or_like('longitud', $q);
	$this->db->or_like('clave', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function desactivar($id)
    {
        
        $this->db->query("UPDATE conductor SET clave='IN' WHERE idconductor=".$id);
    }

}

/* End of file Conductor_model.php */
/* Location: ./application/models/Conductor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-16 17:48:15 */
/* http://harviacode.com */